/**
 * 服务层统一导出
 * 所有API服务在此统一导出，便于组件引用
 */
export { authService } from './auth'
export { projectInfoService } from './projectInfo'
export { periodicInspectionService } from './periodicInspection'
export { temporaryRepairService } from './temporaryRepair'
export { spotWorkService } from './spotWork'
export { workOrderService } from './workOrder'
export { overdueAlertService } from './overdueAlert'
export { expiringSoonService } from './expiringSoon'
export { sparePartsService } from './spareParts'
export { repairToolsService } from './repairTools'
export { weeklyReportService } from './weeklyReport'
export { maintenanceLogService } from './maintenanceLog'
export { operationLogService } from './operationLog'
export { onlineUserService } from './onlineUser'
export { ocrService } from './ocr'
export { uploadService } from './upload'
export { customerService } from './customer'
export { dictionaryService } from './dictionary'
export { inspectionItemService } from './inspectionItem'
export { maintenancePlanService } from './maintenancePlan'
export { personnelService } from './personnel'
export { statisticsService } from './statistics'
export { operationTypeService } from './operationType'
export { userDashboardConfigService } from './userDashboardConfig'
export { workPlanService } from './workPlan'
export { dingtalkService } from './dingtalk'
