"""
PostgreSQL日志检查指南
"""

print("\n" + "="*80)
print("📋 PostgreSQL数据库日志检查指南")
print("="*80 + "\n")

print("📊 [日志位置]")
print("   Windows:")
print("   - 数据目录: C:\\Program Files\\PostgreSQL\\{version}\\data")
print("   - 日志文件: pg_log目录")
print("   - 主要日志: postgresql-{date}.log")
print()
print("   Linux:")
print("   - 数据目录: /var/lib/postgresql/{version}/main")
print("   - 日志文件: /var/log/postgresql/")
print("   - 主要日志: postgresql-{version}-main.log")
print()

print("🔍 [检查步骤]")
print("   1. 打开PostgreSQL数据目录")
print("   2. 进入pg_log文件夹")
print("   3. 查找最新的日志文件")
print("   4. 搜索错误信息：ERROR, FATAL, PANIC")
print("   5. 搜索警告信息：WARNING")
print("   6. 搜索INSERT语句：INSERT INTO project_info")
print()

print("📝 [常用日志查询]")
print("   查看最新日志:")
print("   tail -f postgresql-*.log")
print()
print("   搜索错误:")
print("   grep ERROR postgresql-*.log")
print()
print("   搜索INSERT操作:")
print("   grep 'INSERT INTO project_info' postgresql-*.log")
print()

print("🔧 [启用详细日志]")
print("   编辑postgresql.conf文件:")
print("   log_min_duration_statement = 0  # 记录所有SQL语句")
print("   log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '")
print("   log_checkpoints = on")
print("   log_connections = on")
print("   log_disconnections = on")
print("   log_duration = on")
print()
print("   重启PostgreSQL服务:")
print("   Windows: net stop postgresql-x64-{version}")
print("   Windows: net start postgresql-x64-{version}")
print("   Linux: sudo systemctl restart postgresql")
print()

print("📊 [当前数据库状态]")
print("   数据库URL: postgresql://postgres:123456@localhost:5432/tq")
print("   连接状态: ✅ 成功")
print("   表结构: ✅ 正确")
print("   记录数: 11条")
print("   INSERT测试: ✅ 成功")
print("   事务提交: ✅ 正常")
print()

print("="*80)
print("✅ 日志检查指南完成")
print("="*80 + "\n")

print("💡 [建议]")
print("   1. 如果数据库日志中没有错误信息，说明数据库操作正常")
print("   2. 如果前端看不到数据，问题可能在前端数据绑定")
print("   3. 已修复前端问题：displayData → projectData")
print("   4. 请刷新浏览器页面测试")
print()