/**
 * 类型定义统一导出
 */

export type {
  UserRole,
  RoleCodeType,
  PermissionConfig
} from './permission'

export type {
  ApiResponse,
  PaginatedData,
  PaginatedResponse,
  User,
  UserInfo,
  LoginRequest,
  LoginResponse,
  RefreshTokenResponse
} from './api'

export type {
  SpotWork,
  SpotWorkWorker,
  SpotWorkCreate,
  SpotWorkUpdate,
  SpotWorkQueryParams,
  QuickFillRequest,
  WorkersSaveRequest,
  StatisticsOverview,
  WorkByPerson,
  TopProject,
  ProjectInfo,
  ProjectInfoCreate,
  ProjectInfoUpdate,
  ProjectInfoQueryParams,
  Personnel,
  PersonnelCreate,
  PersonnelUpdate,
  PersonnelQueryParams,
  PeriodicInspection,
  PeriodicInspectionRecord,
  PeriodicInspectionCreate,
  PeriodicInspectionUpdate,
  PeriodicInspectionQueryParams,
  TemporaryRepair,
  TemporaryRepairCreate,
  TemporaryRepairUpdate,
  TemporaryRepairQueryParams,
  SparePartsStock,
  SparePartsUsage,
  SparePartsInbound,
  SparePartsIssueRequest,
  SparePartsReturnRequest,
  SparePartsInboundRequest,
  SparePartsStockQueryParams,
  SparePartsUsageQueryParams,
  MaintenancePlan,
  InspectionItem,
  WeeklyReport,
  MaintenanceLog,
  OperationLog,
  OverdueAlertItem,
  OnlineUser,
  OnlineCount,
  OnlineStatistics,
  DictionaryItem,
  Customer,
  IDCardOCRResult,
  WorkOrderItem,
  WorkOrderQueryParams,
  WorkPlan,
  WorkPlanQueryParams,
  WorkPlanCreate,
  WorkPlanUpdate,
  WorkPlanStatistics,
  WeeklyReportQueryParams,
  WeeklyReportCreate,
  WeeklyReportUpdate,
  MaintenanceLogQueryParams,
  MaintenanceLogCreate,
  MaintenanceLogUpdate,
  RepairToolsStock,
  RepairToolsUsage,
  RepairToolsIssueRequest,
  RepairToolsReturnRequest,
  RepairToolsStockQueryParams,
  RepairToolsUsageQueryParams
} from './models/index'

export {
  RoleCode,
  ADMIN_ROLES,
  ALL_ROLES,
  PROJECT_MANAGEMENT_ROLES,
  PERSONNEL_MANAGEMENT_ROLES,
  SPARE_PARTS_MANAGEMENT_ROLES,
  WORK_ORDER_VIEW_ROLES,
  WORK_ORDER_APPROVE_ROLES,
  STATISTICS_VIEW_ROLES,
  MAINTENANCE_LOG_FILL_ROLES,
  MAINTENANCE_LOG_VIEW_ROLES,
  WEEKLY_REPORT_FILL_ROLES,
  WEEKLY_REPORT_VIEW_ROLES,
  isAdminRole,
  isManagerRole,
  isMaterialManager,
  canDeleteWorkOrder
} from './permission'
