export const ERROR_CODES = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  NETWORK_ERROR: 0,
  TIMEOUT: -1,
  UNKNOWN: -2
} as const

export const ERROR_MESSAGES: Record<number, string> = {
  [ERROR_CODES.SUCCESS]: '操作成功',
  [ERROR_CODES.CREATED]: '创建成功',
  [ERROR_CODES.BAD_REQUEST]: '请求参数错误',
  [ERROR_CODES.UNAUTHORIZED]: '未授权，请重新登录',
  [ERROR_CODES.FORBIDDEN]: '无权限访问',
  [ERROR_CODES.NOT_FOUND]: '资源不存在',
  [ERROR_CODES.METHOD_NOT_ALLOWED]: '请求方法不允许',
  [ERROR_CODES.CONFLICT]: '资源冲突',
  [ERROR_CODES.UNPROCESSABLE_ENTITY]: '数据验证失败',
  [ERROR_CODES.TOO_MANY_REQUESTS]: '请求过于频繁，请稍后再试',
  [ERROR_CODES.INTERNAL_ERROR]: '服务器内部错误',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: '服务暂时不可用',
  [ERROR_CODES.NETWORK_ERROR]: '网络连接失败，请检查网络',
  [ERROR_CODES.TIMEOUT]: '请求超时，请稍后再试',
  [ERROR_CODES.UNKNOWN]: '未知错误'
}

export const BUSINESS_ERROR_CODES = {
  USER_NOT_FOUND: 1001,
  USER_ALREADY_EXISTS: 1002,
  INVALID_PASSWORD: 1003,
  TOKEN_EXPIRED: 1004,
  TOKEN_INVALID: 1005,
  
  PROJECT_NOT_FOUND: 2001,
  PROJECT_ALREADY_EXISTS: 2002,
  
  WORK_ORDER_NOT_FOUND: 3001,
  WORK_ORDER_ALREADY_SUBMITTED: 3002,
  WORK_ORDER_ALREADY_APPROVED: 3003,
  WORK_ORDER_ALREADY_REJECTED: 3004,
  WORK_ORDER_CANNOT_MODIFY: 3005,
  
  SPARE_PARTS_NOT_FOUND: 4001,
  SPARE_PARTS_INSUFFICIENT: 4002,
  SPARE_PARTS_ALREADY_ISSUED: 4003,
  
  OCR_SERVICE_ERROR: 5001,
  OCR_RATE_LIMIT_EXCEEDED: 5002,
  OCR_IMAGE_INVALID: 5003,
  
  FILE_UPLOAD_FAILED: 6001,
  FILE_TOO_LARGE: 6002,
  FILE_TYPE_NOT_ALLOWED: 6003,
  
  SIGNATURE_REQUIRED: 7001,
  PHOTOS_REQUIRED: 7002
} as const

export const BUSINESS_ERROR_MESSAGES: Record<number, string> = {
  [BUSINESS_ERROR_CODES.USER_NOT_FOUND]: '用户不存在',
  [BUSINESS_ERROR_CODES.USER_ALREADY_EXISTS]: '用户已存在',
  [BUSINESS_ERROR_CODES.INVALID_PASSWORD]: '密码错误',
  [BUSINESS_ERROR_CODES.TOKEN_EXPIRED]: '登录已过期，请重新登录',
  [BUSINESS_ERROR_CODES.TOKEN_INVALID]: '登录凭证无效',
  
  [BUSINESS_ERROR_CODES.PROJECT_NOT_FOUND]: '项目不存在',
  [BUSINESS_ERROR_CODES.PROJECT_ALREADY_EXISTS]: '项目编号已存在',
  
  [BUSINESS_ERROR_CODES.WORK_ORDER_NOT_FOUND]: '工单不存在',
  [BUSINESS_ERROR_CODES.WORK_ORDER_ALREADY_SUBMITTED]: '工单已提交，不能重复提交',
  [BUSINESS_ERROR_CODES.WORK_ORDER_ALREADY_APPROVED]: '工单已审批通过',
  [BUSINESS_ERROR_CODES.WORK_ORDER_ALREADY_REJECTED]: '工单已被退回',
  [BUSINESS_ERROR_CODES.WORK_ORDER_CANNOT_MODIFY]: '工单状态不允许修改',
  
  [BUSINESS_ERROR_CODES.SPARE_PARTS_NOT_FOUND]: '备品备件不存在',
  [BUSINESS_ERROR_CODES.SPARE_PARTS_INSUFFICIENT]: '备品备件库存不足',
  [BUSINESS_ERROR_CODES.SPARE_PARTS_ALREADY_ISSUED]: '备品备件已领用',
  
  [BUSINESS_ERROR_CODES.OCR_SERVICE_ERROR]: 'OCR服务异常',
  [BUSINESS_ERROR_CODES.OCR_RATE_LIMIT_EXCEEDED]: 'OCR调用次数超限，请稍后再试',
  [BUSINESS_ERROR_CODES.OCR_IMAGE_INVALID]: '图片格式无效',
  
  [BUSINESS_ERROR_CODES.FILE_UPLOAD_FAILED]: '文件上传失败',
  [BUSINESS_ERROR_CODES.FILE_TOO_LARGE]: '文件大小超过限制',
  [BUSINESS_ERROR_CODES.FILE_TYPE_NOT_ALLOWED]: '文件类型不允许',
  
  [BUSINESS_ERROR_CODES.SIGNATURE_REQUIRED]: '请先完成签名',
  [BUSINESS_ERROR_CODES.PHOTOS_REQUIRED]: '请上传现场照片'
}

export class AppError extends Error {
  code: number
  data?: any
  
  constructor(code: number, message?: string, data?: any) {
    super(message || getErrorMessage(code))
    this.code = code
    this.data = data
    this.name = 'AppError'
  }
}

export function getErrorMessage(code: number): string {
  return BUSINESS_ERROR_MESSAGES[code] || ERROR_MESSAGES[code] || ERROR_MESSAGES[ERROR_CODES.UNKNOWN]
}

export function isError(code: number): boolean {
  return code !== ERROR_CODES.SUCCESS && code !== ERROR_CODES.CREATED
}

export function isAuthError(code: number): boolean {
  return code === ERROR_CODES.UNAUTHORIZED || 
         code === BUSINESS_ERROR_CODES.TOKEN_EXPIRED ||
         code === BUSINESS_ERROR_CODES.TOKEN_INVALID
}

export function isNetworkError(code: number): boolean {
  return code === ERROR_CODES.NETWORK_ERROR || code === ERROR_CODES.TIMEOUT
}

export function isRateLimitError(code: number): boolean {
  return code === ERROR_CODES.TOO_MANY_REQUESTS || 
         code === BUSINESS_ERROR_CODES.OCR_RATE_LIMIT_EXCEEDED
}