/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    HorizontalBarChart: typeof import('./components/HorizontalBarChart.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    PieChart: typeof import('./components/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    Skeleton: typeof import('./components/Skeleton.vue')['default']
    StatCard: typeof import('./components/StatCard.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    VerticalBarChart: typeof import('./components/VerticalBarChart.vue')['default']
  }
}
